FROM python:3.10-slim

WORKDIR /code

COPY requirements-base.in .
COPY requirements.in .
COPY requirements-dev.in .

RUN python -m ensurepip --upgrade
RUN pip install pip-tools
RUN pip-compile --output-file=requirements.txt requirements-base.in requirements-dev.in requirements.in
COPY ./app app/

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]
