version: "3.9"

services:
  api:
    container_name: api
    build:
      context: ../
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://0.0.0.0:8080/"]
      interval: 15s
      timeout: 15s
      retries: 10